### ISSUE TITLE
download link not accessible

### ISSUE THREAD

**Issue by cxxz** [andregraubner/ClimateNet#7]
Hi I was trying to download the dataset but it took forever to open the url: https://portal.nersc.gov/project/ClimateNet/climatenet_new

Could you help me take a look at this issue, please? Your time is greatly appreciated.

**Comment by andregraubner** [comment]
Hey Bill,
I just tried it and am also not able to access the data. This is unexpected behaviour, so I will investigate and then get back to you.

**Comment by cxxz** [comment]
Hi Andre,

The link worked for a while early this morning and stopped working again.

Thanks,
Cong

**Comment by andregraubner** [comment]
Hey Bill, 
I have not heard back from the relevant support so I can't diagnose the problem yet. I assume there's some hosting issues on our side, but I'll let you know as soon as it's resolved or I get more information.

**Comment by cxxz** [comment]
Thank you very much for the update!

Regards,
Cong

**Comment by andregraubner** [comment]
I just got word that the issue is being investigated internally starting now. In the meantime, please let me know if you have any questions regarding the data set, Lukas and me are happy to provide any details you might need.

**Comment by andregraubner** [comment]
The issue should be resolved now. Please let me know if you can access the data set, then I can close this issue. Have a nice day!

**Comment by cxxz** [comment]
Hi Andre,

I am still NOT able to access the link:
https://portal.nersc.gov:8000/project/ClimateNet/climatenet_new/

I tried to open it with Chrome and Safari and both failed.

Regards,
Cong

**Comment by cxxz** [comment]
Yes, I can access the data now! Thank you very much for your time!
